// dataProducts.js

const productsData = [
  {
    id: 1,
    name: "Camiseta Gato na Caixa",
    photo: "assets/produtos/camisetas/cam_gatocaixa.png",
    price: 75.00,
    category: "camiseta",
    description: "Camiseta 100% algodão, confortável e versátil para o dia a dia.",
    sizes: ["P", "M", "G", "GG"] 
  },
  {
    id: 2,
    name: "Camiseta Troca Cultural",
    photo: "assets/produtos/camisetas/cam_trocacultu.png",
    price: 75.00,
    category: "camiseta",
    sizes: ["P", "M", "G", "GG"],
    description: "Camiseta 100% algodão de cor preta, confortável e versátil para o dia a dia"
  },
  {
    id: 3,
    name: "Camiseta Schrödinger",
    photo: "assets/produtos/camisetas/cam_einsten.png",
    price: 75.00,
    category: "camiseta",
    sizes: ["P", "M", "G", "GG"],
    description: "Camiseta 100% algodão, confortável e versátil para o dia a dia"
  },
  {
    id: 4,
    name: "Camiseta Yemoja",
    photo: "assets/produtos/camisetas/cam_yemoja.png",
    price: 75.00,
    category: "camiseta",
    sizes: ["P", "M", "G", "GG"],
    description: "Camiseta 100% algodão, confortável e versátil para o dia a dia"
  },
  {
    id: 5,
    name: "Copo 25 anos WorCAP",
    photo: "assets/produtos/copos/25_anos.gif",
    price: 15.00,
    category: "copo",
    description: "Copo de 500ml edição limitada de 25 anos do WorCAP",
  },
  {
    id: 6,
    name: "Copo Cordel",
    photo: "assets/produtos/copos/Cordel.gif",
    price: 15.00,
    category: "copo",
    description: "Copo de 500ml com temática cordel."
  },
  {
    id: 7,
    name: "Copo Delírio Científico",
    photo: "assets/produtos/copos/Delírio_científico_Translúcio.gif",
    price: 15.00,
    category: "copo",
    description: "Copo Translúcido de 500ml temático Delírio Científico, ilustrando um brainstorms de ideias."
  },
  {
    id: 8,
    name: "Copo Delírio Inpeano",
    photo: "assets/produtos/copos/Delírio_Inpeano.gif",
    price: 15.00,
    category: "copo",
    description: "Copo de 500ml temático Delírio Inpeano, ilustrando a diversidade de áreas de estudo existente no INPE."
  },
  {
    id: 9,
    name: "Caneca 25 anos WorCAP",
    photo: "assets/produtos/canecas/Caneca_25 anos.png",
    price: 45.00,
    category: "caneca",
    description: "Caneca de cerâmica de 300ml com estampa exclusiva de 25 anos do WorCAP, ideal para café ou chá.",
  },
  {
    id: 10,
    name: "Caneca Cordel",
    photo: "assets/produtos/canecas/Caneca_Cordel.png",
    price: 45.00,
    category: "caneca",
    description: "Caneca de cerâmica de 300ml com estampa Cordel, ideal para café ou chá.",
  },
  {
    id: 11,
    name: "Caneca Delírio Científico",
    photo: "assets/produtos/canecas/Caneca_Delírio_Científico.png",
    price: 45.00,
    category: "caneca",
    description: "Caneca de cerâmica de 300ml com estampa exclusiva do Delírio Científico, ideal para café ou chá.",
  },
  {
    id: 12,
    name: "Poster Cordel - Tradicional",
    photo: "assets/produtos/posters/ Cordel.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 13,
    name: "Poster Cordel Foil",
    photo: "assets/produtos/posters/ Cordel Foil.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 14,
    name: "Poster Da Lama ao Caos",
    photo: "assets/produtos/posters/ Da Lama ao Caos.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 15,
    name: "Poster Delírio Científico",
    photo: "assets/produtos/posters/ Delírio Científico.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 16,
    name: "Poster Delírio Inpeano BW",
    photo: "assets/produtos/posters/ Delírio Inpeano BW.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 17,
    name: "Poster Delírio Inpeano",
    photo: "assets/produtos/posters/ Delírio Inpeano.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 18,
    name: "Poster Gato na Caixa",
    photo: "assets/produtos/posters/ Gato na Caixa.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 19,
    name: "Poster LoTR",
    photo: "assets/produtos/posters/ LoTR.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 20,
    name: "Poster Macaconv",
    photo: "assets/produtos/posters/ Mamaco.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 21,
    name: "Poster Método Científico",
    photo: "assets/produtos/posters/ Método Científico.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 22,
    name: "Poster Pioneer 1",
    photo: "assets/produtos/posters/ Pioneer 1.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 23,
    name: "Poster Pioneer 2",
    photo: "assets/produtos/posters/ Pioneer 2.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 24,
    name: "Poster Schrödinger",
    photo: "assets/produtos/posters/ Schrodinger.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 25,
    name: "Poster Troca Cultural",
    photo: "assets/produtos/posters/ Troca Cultural.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  {
    id: 26,
    name: "Poster Yemoja",
    photo: "assets/produtos/posters/ Yemoja.png",
    price: 10.00,
    category: "poster",
    description: "Poster A3 decorativo, sem moldura.",
  },
  
];
